Make a pivot table
1. Insert a pivot table and show "Gross income" for a specific branch
2. In Pivot table, show gross income according to the "Gender" in specific branch
3. In Pivot table, show gross income according to the "Customer type" in specific branch
4. In the Pivot table, show the gross income according to the "Payment" in specific branch

In [1]:
from google.colab import files
uploaded = files.upload()

Saving file.csv to file.csv

In [4]:
import pandas as pd
import io
table = pd.read_csv(io.BytesIO(uploaded['file.csv']))

In [5]:
table

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [6]:
table.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [7]:
table.tail()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [8]:
table.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [9]:
table.isnull()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

Insert a pivot table and show "Gross income" for a specific branch

In [10]:
pivot_table = pd.pivot_table(table, values='gross income', index='Branch', aggfunc='sum', margins=True)

In [11]:
pivot_table

        gross income
Branch
A          5057.1605
B          5057.0320
C          5265.1765
All       15379.3690

In Pivot table, show gross income according to the "Gender" in specific branch

In [15]:
table1 = pd.pivot_table(table, values='gross income', index='Branch', columns='Gender', aggfunc='sum', margins=True)

In [16]:
table1

Gender    Female       Male         All
Branch
A       2536.627  2520.5335   5057.1605
B       2520.395  2536.6370   5057.0320
C       2937.403  2327.7735   5265.1765
All     7994.425  7384.9440  15379.3690

In Pivot table, show gross income according to the "Customer type" in specific branch

In [23]:
table2 = pd.pivot_table(table, values=['gross income'], index=['Customer type','Branch'], columns=['Gender'],aggfunc='sum', margins=True)

In [24]:
table2

                     gross income
Gender                     Female       Male         All
Customer type Branch
Member        A         1268.7175  1285.4480   2554.1655
              B         1278.5920  1278.7740   2557.3660
              C         1650.1640  1058.4685   2708.6325
Normal        A         1267.9095  1235.0855   2502.9950
              B         1241.8030  1257.8630   2499.6660
              C         1287.2390  1269.3050   2556.5440
All                     7994.4250  7384.9440  15379.3690

In the Pivot table, show the gross income according to the "Payment" in specific branch

In [25]:
table3 = table2 = pd.pivot_table(table, values=['gross income'], index=['Payment','Branch',], columns=['Gender'],aggfunc='sum', margins=True)

In [26]:
table3

                   gross income
Gender                   Female       Male         All
Payment     Branch
Cash        A          907.1750   701.4560   1608.6310
            B          834.0005   848.8310   1682.8315
            C         1092.8345   958.8730   2051.7075
Credit card A          718.3225   857.6180   1575.9405
            B          937.5105   840.8160   1778.3265
            C          891.7120   552.4530   1444.1650
Ewallet     A          911.1295   961.4595   1872.5890
            B          748.8840   846.9900   1595.8740
            C          952.8565   816.4475   1769.3040
All                   7994.4250  7384.9440  15379.3690

In [28]:
table4 = table2 = pd.pivot_table(table, values=['gross income'], index=['Payment','Branch','Customer type'], columns=['Gender'],aggfunc='sum', margins=True)

In [29]:
table4

                                 gross income
Gender                                 Female       Male         All
Payment     Branch Customer type
Cash        A      Member            528.1675   313.8655    842.0330
                   Normal            379.0075   387.5905    766.5980
            B      Member            375.5925   429.8590    805.4515
                   Normal            458.4080   418.9720    877.3800
            C      Member            520.7320   434.6890    955.4210
                   Normal            572.1025   524.1840   1096.2865
Credit card A      Member            280.9150   442.9530    723.8680
                   Normal            437.4075   414.6650    852.0725
            B      Member            570.1370   506.4330   1076.5700
                   Normal            367.3735   334.3830    701.7565
            C      Member            625.3030   325.2815    950.5845
                   Normal            266.4090   227.1715    493.5805
Ewallet     A      Member            459.6350   528.6295    988.2645
                   Normal            451.4945   432.8300    884.3245
            B      Member            332.8625   342.4820    675.3445
                   Normal            416.0215   504.5080    920.5295
            C      Member            504.1290   298.4980    802.6270
                   Normal            448.7275   517.9495    966.6770
All                                 7994.4250  7384.9440  15379.3690

In [32]:
table5 = pd.pivot_table(table, values=['gross income'], index=['Payment','Branch','Customer type','City'], columns=['Gender'],aggfunc='sum', margins=True)

In [33]:
table5

                                           gross income
Gender                                           Female       Male         All
Payment     Branch Customer type City
Cash        A      Member        Yangon        528.1675   313.8655    842.0330
                   Normal        Yangon        379.0075   387.5905    766.5980
            B      Member        Mandalay      375.5925   429.8590    805.4515
                   Normal        Mandalay      458.4080   418.9720    877.3800
            C      Member        Naypyitaw     520.7320   434.6890    955.4210
                   Normal        Naypyitaw     572.1025   524.1840   1096.2865
Credit card A      Member        Yangon        280.9150   442.9530    723.8680
                   Normal        Yangon        437.4075   414.6650    852.0725
            B      Member        Mandalay      570.1370   506.4330   1076.5700
                   Normal        Mandalay      367.3735   334.3830    701.7565
            C      Member        Naypyitaw     625.3030   325.2815    950.5845
                   Normal        Naypyitaw     266.4090   227.1715    493.5805
Ewallet     A      Member        Yangon        459.6350   528.6295    988.2645
                   Normal        Yangon        451.4945   432.8300    884.3245
            B      Member        Mandalay      332.8625   342.4820    675.3445
                   Normal        Mandalay      416.0215   504.5080    920.5295
            C      Member        Naypyitaw     504.1290   298.4980    802.6270
                   Normal        Naypyitaw     448.7275   517.9495    966.6770
All                                           7994.4250  7384.9440  15379.3690